name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: |
        cd frontend
        bun install
        
    - name: Run linting
      run: |
        cd frontend
        bun run lint
        
    - name: Run tests
      run: |
        cd frontend
        bun run test --passWithNoTests
        
    - name: Build frontend
      run: |
        cd frontend
        bun run build

  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: |
        cd backend
        bun install
        
    - name: Run linting
      run: |
        cd backend
        bun run lint
        
    - name: Run tests
      run: |
        cd backend
        bun run test --passWithNoTests
        
    - name: Build backend
      run: |
        cd backend
        bun run build

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [test-frontend, test-backend]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install all dependencies
      run: |
        bun install
        cd frontend && bun install
        cd ../backend && bun install
        
    - name: Start backend for testing
      run: |
        cd backend
        bun run dev &
        sleep 10
        
    - name: Test API endpoints
      run: |
        curl -f http://localhost:5000/health || exit 1
        curl -f http://localhost:5000/api || exit 1